alias sv='source .venv/bin/activate'
alias ga='git add .'
alias gac='git add . && git commit -m'
alias gp='git push origin master'
alias pir='pip install -r requirements.txt'
alias vir='virtualenv -p python3 .venv'
